[project]
name = "hf-ai-agent-course-capstone"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=0.3.24",
    "langchain-google-genai>=2.1.3",
    "langchain-mistralai>=0.2.10",
    "langchain-openai>=0.3.14",
    "smolagents==1.13.0",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
